# SPDX-License-Identifier: MIT
---
- name: Restart systemd-networkd
  ansible.builtin.systemd_service:
    name: systemd-networkd.service
    state: restarted

- name: Soft reboot
  ansible.builtin.reboot:
    reboot_command: /usr/bin/systemctl soft-reboot
